### ISSUE TITLE
Plugin doesn't recognize bad passwords the first few times a password is changed

### ISSUE THREAD

**Issue by shanu17** [ulsdevteam/pkp-betterPassword#13]
The first change of password after the plugin is active causes the plugin to fail and the next few times doesnt recognize basic bad passwords. It is rectified after trying to change the password 3-4 times.

**Comment by jonasraoni** [comment]
I've addressed this issue in [this PR](https://github.com/ulsdevteam/pkp-betterPassword/pull/16).
