### ISSUE TITLE
Update the plugin to work with the latest OJS (3.3)

### ISSUE THREAD

**Issue by jonasraoni** [ulsdevteam/pkp-betterPassword#14]
After running the `php tools/upgrade.php upgrade` in a OJS 3.3 instance, I saw the tables were not created.

**Comment by ctgraham** [comment]
`Plugin::getInstallSchemaFile()` is no longer supported in 3.3 with the removal of ADODB.  This will need to be re-written as a Laravel Migration:
https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.3-release-notebook#plugin-schemas

**Comment by ctgraham** [comment]
Resolved by #27.
