### ISSUE TITLE
Add translation to Portuguese.

### ISSUE THREAD

**Issue by LuisLepidus** [ulsdevteam/pkp-betterPassword#26]
Hi,
I would like to contribute by translating the plugin into Brazilian Portuguese.

Cheers,
Luis Leal.

**Comment by ctgraham** [comment]
Thanks, @LuisLepidus .  Looking forward to it!

**Comment by ctgraham** [comment]
@LuisLepidus , are you still interested in submitting this translation?  We are preparing a package with additonal translations at this time.

**Comment by LuisLepidus** [comment]
Sorry for delay but a lot of things happened in the same time, I'LL send the PR in the next 24 hours.

Cheers,
Luis Leal.

**Comment by LuisLepidus** [comment]
> Thanks! Be sure to note some recent changes to correct duplicate keys pointed out by the Turkish contributor: [84d45cd](https://github.com/ulsdevteam/pkp-betterPassword/commit/84d45cd52a0e53204ab535f913c0e9f49484609d)

I checked it!
