### ISSUE TITLE
version.xml invalid

### ISSUE THREAD

**Issue by IgorBaptist4** [ulsdevteam/pkp-betterPassword#29]
End tag for release version doesn't contain "<" of the tag

https://github.com/ulsdevteam/pkp-betterPassword/commit/a2aa449fe4423c17b899a6896dbf9b83a47003d9

**Comment by ctgraham** [comment]
Resolved in https://github.com/ulsdevteam/pkp-betterPassword/commit/59b25f682d68f3a4a4c3ab4a0053fd764e0aab0e
